import Head from "next/head";
import SecTitle from "./components/SecTitle";
import { client } from "../../libs/client";

type blogType = {
  id: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  revisedAt: string;
  title: string;
  slug: string;
  date: string;
  category: {
    id: string;
    createdAt: string;
    updatedAt: string;
    publishedAt: string;
    revisedAt: string;
    category: string;
    slug: string;
  };
  icon: string;
  content: string;
};

export default function Home({ blogs }: blogType[]) {
  return (
    <>
      <Head>
        <title>ポートフォリオ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SecTitle title="new" />
        <ul>
          {blogs.map((blog: blogType) => (
            <li key={blog.id}>
              <a href={`blog/${blog.slug}`}>
                <div>{blog.icon}</div>
                <div>
                  <span>{blog.date}</span>
                  <h2>{blog.title}</h2>
                  <span>{blog.category.category}</span>
                </div>
              </a>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "blog" });

  return {
    props: {
      blogs: data.contents,
    },
  };
};
