import Head from "next/head";
import SecTitle from "./components/SecTitle";
import { client } from "../../libs/client";
import BlogList from "./components/BlogList";
import fetchBlogData from "@/utils/fetchBLogData";
import { blogType } from "../../types/microCms";
import CategoryArea from "./components/CategoryArea";
import Layout from "./components/Layout";

export default function Home({ blogs, categories }: any) {
  return (
    <>
      <Head>
        <title>ポートフォリオ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <BlogList blogs={blogs} categoryName="NEW" />
          <CategoryArea categories={categories} />
        </main>
      </Layout>
    </>
  );
}

export const getStaticProps = async () => {
  const microCmsData = await client.get({ endpoint: "blog" });

  /**
   * 日付の形式を変換
   */
  const data = microCmsData.contents.map((elem: blogType) => {
    const date = new Date(elem.date);
    const formattedDate = `${date.getFullYear()}.${(date.getMonth() + 1)
      .toString()
      .padStart(2, "0")}.${date.getDate().toString().padStart(2, "0")}`;

    return {
      ...elem,
      date: formattedDate,
    };
  });

  //カテゴリ取得
  const categoryArray = await client.get({ endpoint: "category" });

  return {
    props: {
      blogs: data,
      categories: categoryArray.contents,
    },
  };
};
