import Head from "next/head";
import SecTitle from "./components/SecTitle";
import Layout from "./components/Layout";
import styled from "styled-components";
import { COLOR } from "@/styles/variable";
import Image from "next/image";
import { mediaQuery } from "@/utils/breakpoints";

export default function Profile() {
  return (
    <>
      <Head>
        <title>ポートフォリオ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout isProfile>
        <main>
          <SecTitle title="PROFILE" />
          <ProfileLead>
            <ProfileLeadImage>
              <ProfileLeadImageItem src="/img/img_profile.jpg" alt="" fill />
            </ProfileLeadImage>
            <ProfileLeadInfo>
              <ProfileLeadName>モリアツ</ProfileLeadName>
              <ProfileLeadText>
                愛知県出身。現在は山口県のWeb制作会社に勤務。
                <br />
                Next.jsなどモダンな技術を使ったWebアプリ開発に興味があります。
                <br />
                23年の夏までに東京に転職予定です。
              </ProfileLeadText>
            </ProfileLeadInfo>
          </ProfileLead>
          <ProfileList>
            <ProfileItem>
              <ProfileInfoTitle>SKILL</ProfileInfoTitle>
              <ProfileInfoText>
                簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。
              </ProfileInfoText>
            </ProfileItem>

            <ProfileItem>
              <ProfileInfoTitle>HISTORY</ProfileInfoTitle>
              <ProfileInfoText>
                簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。
              </ProfileInfoText>
            </ProfileItem>

            <ProfileItem>
              <ProfileInfoTitle>HOBBY</ProfileInfoTitle>
              <ProfileInfoText>
                簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。簡単なプロフィール文が入ります。
              </ProfileInfoText>
            </ProfileItem>
          </ProfileList>
        </main>
      </Layout>
    </>
  );
}

const ProfileLead = styled.div`
  padding: 0 30px;
  margin-top: 30px;

  ${mediaQuery[0]} {
    display: flex;
    justify-content: center;
    align-items: center;
  }
`;

const ProfileLeadInfo = styled.div`
  ${mediaQuery[0]} {
    /* width: calc(100% - 200px); */
  }
`;

const ProfileLeadText = styled.p`
  margin: 10px auto 0;
  max-width: 450px;

  ${mediaQuery[0]} {
    margin: 5px auto 0;
    font-size: 1.6rem;
  }
`;
const ProfileLeadImage = styled.figure`
  position: relative;
  width: 150px;
  height: 150px;
  margin: 0 auto;
  ${mediaQuery[0]} {
    margin: 0;
    margin-right: 30px;
  }
`;
const ProfileLeadImageItem = styled(Image)`
  object-fit: cover;
  border-radius: 50%;
`;
const ProfileLeadName = styled.h2`
  text-align: center;
  font-size: 2rem;
  margin-top: 10px;
  ${mediaQuery[0]} {
    text-align: left;
  }
`;

const ProfileList = styled.ul`
  display: grid;
  gap: 45px;
  padding: 0 40px;
  margin: 60px auto 0;
  max-width: 800px;
`;

const ProfileItem = styled.li``;

const ProfileInfoTitle = styled.span`
  display: inline-block;
  font-size: 1.6rem;
  background-color: ${COLOR.SECONDARY};
  padding: 2px 20px;
  font-weight: bold;
`;

const ProfileInfoText = styled.p`
  font-size: 1.4rem;
  margin-top: 10px;
`;
