import Head from "next/head";
import SecTitle from "./components/SecTitle";
import Layout from "./components/Layout";
import SecProfile from "./components/SecProfile";

export default function Profile() {
  return (
    <>
      <Head>
        <title>ポートフォリオ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout isProfile>
        <main>
          <SecProfile isProfilePage />
        </main>
      </Layout>
    </>
  );
}
